/* Route batch 10 — the phone app and atwe.com agree about every address.
 *
 * The native app does not keep its own route table: atwe-mobile/src/lib/atwe-routes.js is
 * a generated byte-for-byte copy of public/atwe-routes.js, and the AASA file is generated
 * from the same registry (tools/native-links.js). This file proves:
 *   · every LIVE web route declares exactly one of "opens natively" / "opens in the browser";
 *   · every native target is a screen that genuinely exists in atwe-mobile/app;
 *   · the shipped AASA file, evaluated INDEPENDENTLY with iOS's own rules, hands to the app
 *     exactly the addresses the app claims — and nothing it would not render;
 *   · usernames, legacy aliases, malformed paths, private routes and admin paths behave;
 *   · and (with a database) that a private Beam link still authorises on the server.
 * Everything but the last block needs no database, server or browser.
 */
'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.join(__dirname, '..');
const R = require(path.join(ROOT, 'public', 'atwe-routes.js'));
const NL = require(path.join(ROOT, 'tools', 'native-links.js'));
const MOBILE = path.join(ROOT, 'atwe-mobile');
const AASA = JSON.parse(fs.readFileSync(NL.AASA, 'utf8'));
const COMPONENTS = AASA.applinks.details[0].components;

/* ── An independent AASA evaluator, written from Apple's rules and reading the SHIPPED
   file — not the registry's own appLinkMatch — so a bug in one cannot hide in the other.
   `*` = any run of characters including '/', `?` = exactly one; first match wins;
   a '?' dictionary requires every named query item; no match = not a universal link. */
function iosAllows(pathname, search) {
  const q = new URLSearchParams(search || '');
  for (const c of COMPONENTS) {
    const re = (g) => new RegExp('^' + g.split('').map((ch) => ch === '*' ? '.*' : ch === '?' ? '.' : ch.replace(/[.+^${}()|[\]\\]/g, '\\$&')).join('') + '$', c.caseSensitive === false ? 'i' : '');
    if (!re(c['/']).test(pathname)) continue;
    if (c['?'] && !Object.entries(c['?']).every(([k, v]) => q.has(k) && re(v).test(q.get(k)))) continue;
    return !c.exclude;
  }
  return false;
}

/* ── Does a native target name a screen that exists in atwe-mobile/app? expo-router:
   (group) folders vanish, index is the folder, [x] is a dynamic segment. */
const SCREENS = (() => {
  const out = [];
  const walk = (dir, rel) => fs.readdirSync(dir, { withFileTypes: true }).forEach((e) => {
    const r = rel.concat(e.name);
    if (e.isDirectory()) return walk(path.join(dir, e.name), r);
    if (!/\.tsx$/.test(e.name) || e.name.startsWith('_')) return;
    const segs = r.map((s) => s.replace(/\.tsx$/, '')).filter((s) => !/^\(.*\)$/.test(s));
    if (segs[segs.length - 1] === 'index') segs.pop();
    out.push(segs);
  });
  walk(path.join(MOBILE, 'app'), []);
  return out;
})();
const settingsIds = [...fs.readFileSync(path.join(MOBILE, 'src/settings/pages.ts'), 'utf8').matchAll(/\{ id: '([a-z-]+)'/g)].map((m) => m[1]);
const meIds = [...fs.readFileSync(path.join(MOBILE, 'src/me/sections.ts'), 'utf8').matchAll(/^\s+id: '([a-z-]+)'/gm)].map((m) => m[1]);
function screenFor(target) {
  const segs = target.split('?')[0].split('/').filter(Boolean);
  return SCREENS.find((s) => s.length === segs.length && s.every((f, i) => {
    const t = segs[i];
    if (/^\[.+\]$/.test(f)) {
      if (t.startsWith(':')) return true;
      // A literal value in a dynamic slot must be one that screen accepts.
      if (s[0] === 'settings') return settingsIds.includes(t);
      if (s[0] === 'me') return meIds.includes(t);
      return false;
    }
    return f === t;
  })) || null;
}

/* A sample canonical address for every live route. */
const SAMPLE = { int: '42', handle: 'samantha.lee', slug: 'my-club', idslug: '42-blue-mug' };
function sample(route) {
  const params = {};
  Object.entries(route.params).forEach(([k, spec]) => { params[k] = Array.isArray(spec) ? spec[0] : SAMPLE[spec]; });
  return R.build(route.name, params);
}
const LIVE = R.liveRoutes();

test('every live route declares native OR browser — none falls through', () => {
  const bad = LIVE.filter((r) => !(r.native === R.BROWSER || typeof r.native === 'string' || (r.native && r.native.resolve && r.native.to)));
  assert.deepEqual(bad.map((r) => r.name), []);
  assert.deepEqual(Object.keys(R.NATIVE).filter((n) => !R.get(n) || R.get(n).status !== 'live'), [], 'NATIVE names a route that is not live');
});

test('every native target is a screen that exists in atwe-mobile/app', () => {
  const missing = [];
  LIVE.forEach((r) => {
    if (r.native === R.BROWSER) return;
    const t = typeof r.native === 'string' ? r.native : r.native.to;
    if (!screenFor(t)) missing.push(r.name + ' -> ' + t);
  });
  assert.deepEqual(missing, []);
});

test('the shipped AASA and the app copy are generated from the registry, byte for byte', () => {
  const want = NL.expected();
  assert.equal(fs.readFileSync(NL.AASA, 'utf8'), want[NL.AASA], 'AASA is stale: node tools/native-links.js');
  assert.equal(fs.readFileSync(NL.COPY, 'utf8'), fs.readFileSync(NL.SRC, 'utf8'), 'the app copy differs from public/atwe-routes.js');
  assert.deepEqual(AASA.applinks.details[0].appIDs, ['TH3FQ8FMKB.com.atwe.app']);
  assert.ok(Buffer.byteLength(want[NL.AASA]) < 128 * 1024, 'Apple refuses an AASA over 128KB');
  assert.ok(!('paths' in AASA.applinks.details[0]), 'the old claim-everything `paths` list is gone');
});

test('every canonical route: one decision, and the iPhone agrees with the app', () => {
  LIVE.forEach((r) => {
    const p = sample(r);
    const l = R.nativeLink('https://atwe.com' + p);
    assert.ok(l, r.name + ': ' + p + ' returned null');
    const wantNative = r.native !== R.BROWSER;
    if (wantNative) {
      assert.ok(l.kind === 'native' || l.kind === 'resolve', r.name + ' ' + p + ' -> ' + JSON.stringify(l));
      assert.equal(l.route, r.name, p);
    } else {
      assert.equal(l.kind, 'browser', r.name + ' ' + p + ' -> ' + JSON.stringify(l));
    }
    assert.equal(iosAllows(p, ''), wantNative, 'AASA disagrees for ' + r.name + ' ' + p);
  });
});

test('every legacy alias lands where its canonical address lands', () => {
  LIVE.forEach((r) => r.aliases.forEach((a) => {
    const params = {};
    Object.entries(r.params).forEach(([k, spec]) => { params[k] = Array.isArray(spec) ? spec[0] : SAMPLE[spec]; });
    const p = a.split('/').map((s) => s.startsWith(':') ? params[s.slice(1)] || SAMPLE.int : s).join('/');
    if (p === '/go') { // server-owned shell path: browser, as the server keeps it
      assert.equal(R.nativeLink(p).kind, 'browser'); assert.equal(iosAllows(p, ''), false); return;
    }
    const la = R.nativeLink('https://atwe.com' + p), lc = R.nativeLink('https://atwe.com' + sample(r));
    assert.equal(la.kind, lc.kind, a);
    if (la.kind === 'native') assert.equal(la.path, lc.path, a);
    if (la.kind === 'browser' && R.legacyRedirect(p)) assert.equal(la.url, 'https://atwe.com' + R.legacyRedirect(p), a);
  }));
});

/* A corpus: every sample, every alias, the server's own paths, files, reserved words,
   queries, junk, and a seeded fuzz of shapes. For EVERY one, the shipped AASA (read by
   the independent evaluator) and the app's own decision must agree. */
function corpus() {
  const out = new Set(['/', '/beam/', '/engine/', '/x/', '//', '/%zz', '/%40sam', '/@sam', '/admin', '/admin.html',
    '/api/admin/users', '/api/atchat/peer/sam', '/.well-known/apple-app-site-association', '/__shell/1', '/_diag',
    '/catalog/x.json', '/s/abc', '/go', '/sw.js', '/manifest.json', '/terms.html', '/privacy.html', '/status',
    '/security', '/robots.txt', '/john.doe', '/john.png', '/a', '/John', '/john/post/5/photo/1', '/john/posts',
    '/john/connections', '/john/random', '/listing/abc', '/listing/12/old', '/beam/u/', '/beam/u/sam/x', '/beam/g/x',
    '/beam/g/1/info/x', '/settings/nope', '/settings/security/nope', '/account/nope', '/engine/nope', '/engine/search',
    '/engine/workers', '/communities/abc', '/newsletter/1/issue/x', '/showcase/abc', '/group', '/circle', '/post/abc',
    '/official', '/staff', '/register', '/shop', '/user/sam', '/chat/12', '/story/3']);
  LIVE.forEach((r) => { out.add(sample(r)); r.aliases.forEach((a) => out.add(a.replace(/:[a-z]+/g, '7'))); });
  let seed = 10;
  const rnd = () => { seed = (seed * 1103515245 + 12345) % 2147483648; return seed / 2147483648; };
  const atoms = ['beam', 'u', 'g', 'engine', 'account', 'settings', 'listing', 'post', 'sam', '12', '12-x', 'info',
    'store', 'orders', 'admin', 'api', 'media', 'posts', 'issue', 'privacy', 'devices', 'x.png', 'Sam', '%41'];
  for (let i = 0; i < 1500; i++) {
    const n = 1 + Math.floor(rnd() * 4);
    out.add('/' + Array.from({ length: n }, () => atoms[Math.floor(rnd() * atoms.length)]).join('/'));
  }
  return [...out];
}
const QUERIES = ['', '?utm_source=x', '?paylink=abc', '?token=t', '?ref=friend', '?u=sam', '?next=%2Fbeam', '?tab=x'];

test('AASA ⇔ app: the iPhone hands over exactly what the app claims (corpus × queries)', () => {
  let n = 0;
  for (const p of corpus()) for (const q of QUERIES) {
    n++;
    const l = R.nativeLink('https://atwe.com' + p + q);
    assert.ok(l, p + q);
    const app = l.kind !== 'browser';
    assert.equal(iosAllows(p, q.slice(1)), app, 'disagree on ' + p + q + ' -> ' + JSON.stringify(l));
    assert.equal(R.appLinkAllows(p, q), app, p + q);
    if (app) assert.ok(['native', 'resolve', 'notfound'].includes(l.kind), p + q);
  }
  assert.ok(n > 5000, 'corpus too small: ' + n);
});

test('the historical bugs are fixed', () => {
  // canonical post-with-author opens the native post
  assert.deepEqual(R.nativeLink('https://atwe.com/sam/post/5'), { kind: 'native', path: '/post/5', route: 'post' });
  assert.deepEqual(R.nativeLink('https://atwe.com/post/5'), { kind: 'native', path: '/post/5', route: 'post' });
  // the old native handle rule (^[a-z0-9_]{2,30}$) rejected valid web handles
  for (const h of ['a', 'john.doe', 'john-doe', 'x'.repeat(40), 'ab_c']) {
    assert.deepEqual(R.nativeLink('https://atwe.com/' + h), { kind: 'native', path: '/user/' + h, route: 'profile' }, h);
  }
  // http://localhost/ is not ours and must never become a profile
  assert.equal(R.nativeLink('http://localhost/'), null);
  assert.equal(R.nativeLink('https://evil.example/sam'), null);
  // unsupported web links are NOT captured by the iPhone
  for (const p of ['/group/my-club', '/circle/chefs', '/settings/security/devices', '/reset-password', '/verify-email',
    '/login', '/beam/u/sam/3', '/beam/g/9/info', '/sam/media', '/help', '/account/ads', '/collections']) {
    assert.equal(iosAllows(p, ''), false, p);
    assert.equal(R.nativeLink('https://atwe.com' + p).kind, 'browser', p);
  }
  // a web action in the query always stays in the browser, on any path
  for (const u of ['/?paylink=abc', '/?verify=t', '/listing/1?checkout=success', '/?u=sam', '/?ref=x'])
    assert.equal(R.nativeLink('https://atwe.com' + u).kind, 'browser', u);
});

test('usernames: the app accepts exactly what the web router accepts', () => {
  // The web's REAL parser, extracted from the shipped index.html.
  const html = fs.readFileSync(path.join(ROOT, 'public', 'index.html'), 'utf8');
  const i = html.indexOf('const APP_ROUTES = {'), j = html.indexOf('/* Turn a parsed route into the surface');
  assert.ok(i > -1 && j > i);
  const ctx = { location: { pathname: '/' }, requestAnimationFrame: () => 0, console };
  vm.createContext(ctx);
  vm.runInContext(html.slice(i, j) + '\nthis.__p = () => parseDeepLink();', ctx);
  const web = (p) => { ctx.location.pathname = p; const d = ctx.__p(); return d && d.type === 'profile' && !d.section ? String(d.username).toLowerCase() : null; };
  const names = ['a', 'ab', 'a1', '1', 'john.doe', 'john-doe', 'john_doe', 'x'.repeat(40), 'x'.repeat(41),
    '.john', 'john.', '-john', 'john-', '_john', 'john_', 'a..b', 'John', 'JOHN.Doe', '@sam', 'sa m', 'sam!',
    'settings', 'beam', 'engine', 'account', 'official', 'staff', 'api', 'admin', 'shop', 'service', 'go', 'me'];
  for (const n of names) {
    const p = '/' + encodeURIComponent(n).replace(/%40/, '@');
    const l = R.nativeLink('https://atwe.com' + p);
    const native = l && l.kind === 'native' && l.route === 'profile' ? decodeURIComponent(l.path.slice('/user/'.length)) : null;
    assert.equal(native, web(p), 'parity on ' + n);
  }
  // case is canonicalised to lower-case, a leading @ dropped
  assert.equal(R.nativeLink('https://atwe.com/JOHN.Doe').path, '/user/john.doe');
  assert.equal(R.nativeLink('https://atwe.com/@sam').path, '/user/sam');
  // the rule for a NEW username is the same shared function the server enforces
  for (const [n, ok] of [['a', true], ['john.doe', true], ['john-doe', true], ['john_doe', true], ['x'.repeat(40), true],
    ['x'.repeat(41), false], ['.john', false], ['john.', false], ['-john', false], ['john_', false], ['a..b', false], ['john.png', false]]) {
    assert.equal(R.usernameShapeError(n) === null, ok, n);
  }
  // reserved roots are never a profile, in the app or on the iPhone
  for (const w of ['settings', 'beam', 'engine', 'account', 'official', 'staff', 'api', 'admin', 'register']) {
    const l = R.nativeLink('https://atwe.com/' + w);
    assert.ok(!(l.kind === 'native' && l.route === 'profile'), w);
  }
});

test('private routes never open natively without a server check; admin is never claimed', () => {
  // A DM address carries a username; the app must ask the server (the authorising lookup).
  const dm = R.nativeLink('https://atwe.com/beam/u/Sam');
  assert.deepEqual(dm, { kind: 'resolve', resolve: 'peer', value: 'sam', to: '/chat/:peer', route: 'beam-dm' });
  // A group conversation opens the member-only native screen, which fetches
  // /api/atchat/groups/:id — the server 404s a non-member exactly as a missing group.
  assert.equal(R.nativeLink('https://atwe.com/beam/g/9').path, '/group/9');
  const src = fs.readFileSync(path.join(ROOT, 'server.js'), 'utf8');
  const g = src.slice(src.indexOf("app.get('/api/atchat/groups/:id'"), src.indexOf("app.get('/api/atchat/groups/:id'") + 1500);
  assert.match(g, /isGroupMember\(gid, req\.user\.id\)\)\) return res\.status\(404\)\.json\(\{ error: 'Group not found\.' \}\)/);
  assert.match(g, /if \(!g\.rows\[0\]\) return res\.status\(404\)\.json\(\{ error: 'Group not found\.' \}\)/);
  // Nothing under /api or /admin is ever handed to the app.
  const allows = COMPONENTS.filter((c) => !c.exclude).map((c) => c['/']);
  assert.ok(!allows.some((a) => /^\/(api|admin)/i.test(a)), allows.join(' '));
  for (const p of ['/admin', '/admin/', '/admin.html', '/api/admin/users', '/API/x']) assert.equal(iosAllows(p, ''), false, p);
  // every Account/Settings address in the app is a signed-in screen (the auth guard in _layout)
  const layout = fs.readFileSync(path.join(MOBILE, 'app/_layout.tsx'), 'utf8');
  assert.match(layout, /if \(!signedIn\) return;\s*const run = \(full/);
  assert.match(layout, /if \(!signedIn && !inAuth\) router.replace\(.\/\(auth\)\/login.\)/);
});

test('the native app uses the shared table and nothing else', () => {
  const dl = fs.readFileSync(path.join(MOBILE, 'src/lib/deeplinks.ts'), 'utf8');
  assert.match(dl, /from '\.\/atwe-routes'/);
  assert.ok(!/case 'user'|case 'chat'|\[a-z0-9_\]\{2,30\}/.test(dl), 'a second hand-written route table crept back');
  assert.match(dl, /\/api\/atchat\/peer\//);
  // System URLs (universal links, atwe://) are rewritten BEFORE expo-router routes them by
  // file path, or atwe.com/john would land on the router's "Unmatched Route" page first.
  const intent = fs.readFileSync(path.join(MOBILE, 'app/+native-intent.tsx'), 'utf8');
  assert.match(intent, /export function redirectSystemPath[\s\S]*systemPath\(path, initial\)/);
  assert.match(dl, /export function systemPath[\s\S]*l\.kind === 'native' \|\| l\.kind === 'notfound'\) return l\.path;/);
  const app = JSON.parse(fs.readFileSync(path.join(MOBILE, 'app.json'), 'utf8')).expo;
  assert.ok((app.ios.associatedDomains || []).includes('applinks:atwe.com'), 'universal links need the associated domain');
  // Android: every host the app's intent filter claims is one the shared parser treats as Atwe.
  const hosts = (app.android.intentFilters || []).flatMap((f) => (f.data || []).map((d) => d.host));
  hosts.forEach((h) => assert.ok(R.OWN_HOSTS.includes(h), h));
  // the app scheme and a push payload's bare path go through the same parser
  assert.equal(R.nativeLink('atwe://beam').path, '/beam');
  assert.equal(R.nativeLink('/').path, '/');
  assert.equal(R.nativeLink('/admin.html').kind, 'browser');
  assert.equal(R.nativeLink('https://atwe.ai/').path, '/ai');
  assert.equal(R.nativeLink('https://www.atwe.com/listing/3-x').path, '/listing/3');
});

/* ── With a database: the server half of the privacy promise. ── */
const H = require('./helpers');
const live = { skip: H.SKIP ? 'no TEST_DATABASE_URL/DATABASE_URL set' : false };
test('a private Beam link still authorises on the server after hand-off', live, async (t) => {
  await H.startServer();
  t.after(() => H.stopServer());
  const db = H.getPool();
  const me = await H.seedUser(), friend = await H.seedUser(), ghost = await H.seedUser(), stranger = await H.seedUser();
  const tok = await H.login(me);
  await db.query('UPDATE users SET deactivated = true WHERE id = $1', [ghost.id]);
  // The DM lookup a native link performs.
  const ok = await H.api('GET', '/api/atchat/peer/' + friend.username.toUpperCase(), { token: tok });
  assert.equal(ok.status, 200); assert.equal(ok.body.id, friend.id);
  const none = await H.api('GET', '/api/atchat/peer/nobody_' + Date.now(), { token: tok });
  const gone = await H.api('GET', '/api/atchat/peer/' + ghost.username, { token: tok });
  assert.equal(none.status, 404); assert.equal(gone.status, 404);
  assert.deepEqual(gone.body, none.body, 'a deactivated stranger and a missing handle must be indistinguishable');
  assert.equal((await H.api('GET', '/api/atchat/peer/' + friend.username)).status, 401, 'signed-out lookup refused');
  // A group the member is not in reads exactly like one that does not exist.
  const gid = (await db.query("INSERT INTO at_groups (name, created_by) VALUES ('Private B10', $1) RETURNING id", [stranger.id])).rows[0].id;
  await db.query('INSERT INTO at_group_members (group_id, user_id) VALUES ($1, $2)', [gid, stranger.id]);
  const foreign = await H.api('GET', '/api/atchat/groups/' + gid, { token: tok });
  const missing = await H.api('GET', '/api/atchat/groups/' + (gid + 100000), { token: tok });
  assert.equal(foreign.status, 404); assert.equal(missing.status, 404);
  assert.deepEqual(foreign.body, missing.body);
  assert.ok(!JSON.stringify(foreign.body).includes('Private B10'));
});
